### PR TITLE
matrix: Add initial docs (closes #11)

### LINKED ISSUE #11: Document Matrix/Riot service
_Related to FOSSRIT/tasks#107._

---

Explain our Matrix presence (rooms, communities, integrations) and how to manage them.

### PR DESCRIPTION
**Pull request by jwflory**
This commit is a first-pass explainer to what Matrix/Riot are and how we use them in the FOSS@RIT community. It also collects some of the rooms I know about but is probably not a complete list.

Closes #11.

I'd like to get two, or maybe even three, reviews on this doc since a lot of folks use Matrix in our community. I requested a review from Tech Team, but also tagged a few people whose eyes I'd like to borrow. :eyes: 

Screenshot of rendered page from local development environment

### CODE REVIEW

**Comment by Alch-Emi** [comment]
> Response to an informal invitation to review

Looks good to me!

There's a few small things I might change/add.  (None of very high importance, though)

* I might note that communities as they are currently implemented are not long for this world, and will be replaced with Groups-As-Rooms once [MSC 1772](https://github.com/matrix-org/matrix-doc/pull/1772) gets merged
* Also, it's kinda a small thing, but I have a really hard time reading the last sentence of the *How we use matrix paragraph*, even knowing what you're trying to say. Maybe something like "Many of our users use the Matrix network, but can communicate seamlessly with the IRC rooms", if I understood your original meaning correctly?
* It might be useful to add a super short blurb to the "Known Rooms" table with a description of each room. It's not super important, since you can kinda tell based off of the name of the room, but it could also help make it a little bit more clear.

All of that is really just clarity though, and whether or not you want to add them is up to you. Overall, I think it works really well and is a really good description of the relation of FOSS and Matrix

* * *

**Addendum:** The Riot screenshot used to illustrate communities uses the legacy Riot client, which is most likely not what new Riot users will be using/seeing.  It might be helpful to use a screenshot from the redesigned client, so that users might better understand it in context.  Something like the attached might be good, though feel free to use a different screenshot, ofc

A screenshot of the updated Riot.im interface, with the "communities" button highlighted

**Comment by jwflory** [comment]
Thanks for reviewing @Alch-Emi! :+1: I addressed most of your feedback in commit fd891c6482302bca051a9a382df21248a8579d4d. I decided against adding the description field to the known rooms, because of a limitation where the tables will flow off-screen if too much text is added. I think the room preview in Matrix/Riot will be enough for most cases.

**Comment by jwflory** [comment]
Thanks @ct-martin, I addressed your feedback in commit 99d8842268c15698aaa2c2c8be89879232e96454. :+1:

**Comment by Tjzabel** [comment]
@Alch-Emi what do you mean, legacy Riot client?

**Comment by jwflory** [comment]
Thanks everyone for the detailed reviews and feedback! :tada: I am happy with the feedback collected so far, so I'm going to rebase and merge this PR. :clapper: 

> **@jibby0**:
> The `IRC (Freenode)` link under `How we use Matrix` (https://github.com/FOSSRIT/runbook/blob/master/docs/infra/irc) brings me to a 404

On GitHub.com this won't work, but when the docs are built and rendered on https://runbook.fossrit.community, this becomes an internal link to the IRC page. When I built them locally, it took me to the right place. :smile:

**Pull request merged**
